### ISSUE TITLE
Web Interface Technologies

### ISSUE THREAD

**Issue by schae234** [monprin/geneWordSearch#5]
Hi Joe,

To get started with the web implementation, have a look over these vital libraries:

+ [flask](http://flask.pocoo.org/) -- essential for making the site dynamic and making javascript talk to python.
+ [ajax with jquery](https://jquery.com/) -- Easily manipulate the DOM and send data back and forth between client and server.
+ [bootstrap](http://getbootstrap.com/) <- I've just started playing around with this, I like it so far! 
+ [DataTables](https://www.datatables.net/) -- Pretty cool html table abstraction. I'm not totally sold on this one, I am currently shopping around for a better library (or it could be that I'm not using this one right), my version currently chokes on huge datasets.

When I started making sites, I HATED using libraries. I thought that vanilla javascript was better. I learned a lot, but ultimately ended up writing pretty awful code. I've since learned that someone else has probably done it, and done it better, but as always this is your project so it's up to you on how to implement things. If you like another toolset better (e.g. django over flask, plain old AJAX, whatever fancy pants, hipster javascript library is hot right now) feel free to use it! 

 As a use case, I think we should implement a simple interface like we have in the CLI.py. As we talked about before with the CLI, try to keep your interface code as a separate entity from the actual python classes. i.e. don't muddle your core geneWordSearch classes with xxx.create_html_table_from_POST() methods. Create an HTML page that sends an AJAX request to a flask app which in turn handles the request by importing geneWordSearch and doing all the footwork there (i.e. interface code stays in the interface). Maybe for now, to keep things simple, install flask etc etc on your local machine and I will work on getting it all kosher on our web server. Right now its all jerry rigged together from the last time I did something using flask.

Let me know if this makes any sense.

**Comment by monprin** [comment]
Made website
